body:
  - type: dropdown
    id: os
    attributes:
      label: What system are you running Yazi on?
      options:
        - Linux X11
        - Linux Wayland
        - macOS
        - Windows
        - Windows WSL
        - FreeBSD X11
        - FreeBSD Wayland
        - Android
    validations:
      required: true
  - type: input
    id: terminal
    attributes:
      label: What terminal are you running Yazi in?
      placeholder: "ex: kitty v0.32.2"
    validations:
      required: true
  - type: textarea
    id: debug
    attributes:
      label: "`yazi --debug` output"
      description: Please run `yazi --debug` and paste the debug information here.
      render: Shell
    validations:
      required: true
  - type: textarea
    id: description
    attributes:
      label: Describe the question
      description: A clear and concise description of what the question is
      placeholder: Tell us what you want to know
    validations:
      required: true
  - type: textarea
    id: other
    attributes:
      label: Anything else?
      description: |
        Add any other context about the problem here.  You can attach screenshots by clicking
        this area to highlight it and then drag the files in.
  - type: checkboxes
    id: checklist
    attributes:
      label: Checklist
      description: Before submitting the post, please make sure you have completed the following
      options:
        - label: I have read all the documentation
          required: true
        - label: I have searched the existing discussions/issues
          required: true
