name: 🐞 Bug Report
description: Create a report to help us improve
labels: [bug]
assignees: []
body:
  - type: dropdown
    id: os
    attributes:
      label: What system are you running Yazi on?
      options:
        - Linux X11
        - Linux Wayland
        - macOS
        - Windows
        - Windows WSL
        - FreeBSD X11
        - FreeBSD Wayland
        - Android
    validations:
      required: true
  - type: input
    id: terminal
    attributes:
      label: What terminal are you running Yazi in?
      placeholder: "ex: kitty v0.32.2"
    validations:
      required: true
  - type: textarea
    id: debug
    attributes:
      label: "`yazi --debug` output"
      description: Please run `yazi --debug` and paste the debug information here.
      render: Shell
    validations:
      required: true
  - type: textarea
    id: description
    attributes:
      label: Describe the bug
      description: A clear and concise description of what the bug is
      placeholder: Tell us what happened
    validations:
      required: true
  - type: textarea
    id: reproducer
    attributes:
      label: Minimal reproducer
      description: A [minimal reproducer](https://stackoverflow.com/help/minimal-reproducible-example) is required, otherwise the issue might be closed without further notice.
      placeholder: |
        Please include as much information as possible that can help to reproduce and understand the issue.
    validations:
      required: true
  - type: textarea
    id: other
    attributes:
      label: Anything else?
      description: |
        Add any other context about the problem here.  You can attach screenshots by clicking
        this area to highlight it and then drag the files in.
  - type: checkboxes
    id: checklist
    attributes:
      label: Checklist
      description: Before submitting the issue, please make sure you have completed the following
      options:
        - label: I tried the [latest nightly build](https://yazi-rs.github.io/docs/installation#binaries), and the issue is still reproducible
          required: true
        - label: I updated the debug information (`yazi --debug`) input box to the nightly that I tried
          required: true
        - label: I can reproduce it after disabling all custom configs/plugins (`mv ~/.config/yazi ~/.config/yazi-backup`)
