name: 🐞 Bug Report
description: Create a report to help us improve
labels: [bug]
assignees: []
body:
  - type: dropdown
    id: os
    attributes:
      label: What system are you running Yazi on?
      options:
        - Linux X11
        - Linux Wayland
        - macOS
        - Windows
        - Windows WSL
        - FreeBSD X11
        - FreeBSD Wayland
    validations:
      required: true
  - type: input
    id: terminal
    attributes:
      label: What terminal are you running Yazi in?
      placeholder: "ex: kitty v0.32.2"
    validations:
      required: true
  - type: textarea
    id: debug
    attributes:
      label: "`yazi --debug` output"
      description: Please run `yazi --debug` and paste the debug information here.
      render: Shell
    validations:
      required: true
  - type: dropdown
    id: tried_main
    attributes:
      label: Did you try the latest nightly build to see if the problem got fixed?
      options:
        - Yes, and I updated the debug information above (`yazi --debug`) to the nightly that I tried
        - No, and I'll explain why below
    validations:
      required: true
  - type: textarea
    id: description
    attributes:
      label: Describe the bug
      description: A clear and concise description of what the bug is
      placeholder: Tell us what happened
    validations:
      required: true
  - type: textarea
    id: reproducer
    attributes:
      label:  Minimal reproducer
      description: A [minimal reproducer](https://stackoverflow.com/help/minimal-reproducible-example) is required, otherwise the issue might be closed without further notice.
      placeholder: |
        Please include as much information as possible that can help to reproduce and understand the issue.
    validations:
      required: true
  - type: textarea
    id: other
    attributes:
      label: Anything else?
      description: |
        Add any other context about the problem here.  You can attach screenshots by clicking
        this area to highlight it and then drag the files in.
