name: Feature Request
description: Suggest an idea for this project
labels: [feature]
assignees: []
body:
  - type: textarea
    id: problem
    attributes:
      label: Please describe the problem you're trying to solve
      description: A clear and concise description of what the problem is. Ex. I'm always frustrated when [...]
    validations:
      required: true
  - type: checkboxes
    id: contribute
    attributes:
      label: Would you be willing to contribute this feature?
      description: The feature has a much higher chance of completion if you are willing to get involved!
      options:
        - label: Yes, I'll give it a shot
  - type: textarea
    id: solution
    attributes:
      label: Describe the solution you'd like
      description: A clear and concise description of what you want to happen.
    validations:
      required: true
  - type: textarea
    id: context
    attributes:
      label: Additional context
      description: Add any other context or screenshots about the feature request here.
