[unstable]
trim-paths = true

[profile.release]
trim-paths = "all"

[target.'cfg(all())']
rustflags = [
	"-Cpasses=mergefunc",
	"-Zunstable-options",
	"-Zshare-generics=true",
]

# LLD lacks the SPARC GOTDATA_OP relocations emitted by GCC.
[target.'cfg(all(target_os = "linux", not(target_arch = "sparc64")))']
rustflags = [
	"-Clinker-features=+lld",
	"-Clink-arg=-Wl,--icf=safe",
	"-Clink-arg=-Wl,-z,pack-relative-relocs",
]

[target.'cfg(target_os = "macos")']
rustflags = [ "-Clink-arg=-Wl,-O1" ]
