[package]
name                   = "yazi-emulator"
description            = "Yazi terminal emulator database"
version.workspace      = true
edition.workspace      = true
license.workspace      = true
authors.workspace      = true
homepage.workspace     = true
repository.workspace   = true
rust-version.workspace = true

[lints]
workspace = true

[dependencies]
yazi-macro  = { path = "../yazi-macro", version = "26.8.15" }
yazi-shared = { path = "../yazi-shared", version = "26.8.15" }
yazi-shim   = { path = "../yazi-shim", version = "26.8.15" }
yazi-term   = { path = "../yazi-term", version = "26.8.15" }
yazi-tty    = { path = "../yazi-tty", version = "26.8.15" }

# External dependencies
anyhow   = { workspace = true }
arc-swap = { workspace = true }
tokio    = { workspace = true }
