name: Cachix
on:
  push:
    branches:
      - main

jobs:
  publish:
    name: Publish Flake
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4

      - name: Install Nix
        uses: cachix/install-nix-action@v25

      - name: Authenticate with Cachix
        uses: cachix/cachix-action@v14
        with:
          name: yazi
          authToken: "${{ secrets.CACHIX_AUTH_TOKEN }}"

      - name: Build Flake
        run: nix build -L
