name: Moderate

on:
  issues:
    types: [labeled]
  pull_request_target:
    types: [labeled]
  schedule:
    - cron: "30 * * * *"
  workflow_dispatch:

jobs:
  moderate:
    permissions:
      contents: read
      issues: write
      pull-requests: write
    uses: yazi-rs/.github/.github/workflows/moderate.yml@main
