name: Publish

on:
  release:
    types: [published]

jobs:
  winget:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v4
        with:
          merge-multiple: true

      - name: Publish to Winget
        uses: vedantmgoyal9/winget-releaser@main
        with:
          identifier: sxyazi.yazi
          installers-regex: 'yazi-(x86_64|aarch64)-pc-windows-msvc\.zip$'
          token: ${{ secrets.WINGET_TOKEN }}

      - name: Promote snap to stable
        env:
          SNAPCRAFT_STORE_CREDENTIALS: ${{ secrets.SNAPCRAFT_TOKEN }}
        run: |
          sudo snap install --classic snapcraft
          snapcraft promote yazi --from-channel latest/candidate --to-channel latest/stable --yes
