name: Test

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  SCCACHE_GHA_ENABLED: true
  RUSTC_WRAPPER: sccache
  CARGO_TERM_COLOR: always

permissions:
  contents: read

jobs:
  test:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v7

      - name: Setup Rust toolchain
        run: rustup toolchain install stable --profile minimal

      - name: Setup sccache
        uses: mozilla-actions/sccache-action@v0.0.11

      - name: Build
        run: cargo build --verbose

      - name: Test
        run: cargo test --workspace --verbose

  test-freebsd:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7

      - name: Test in FreeBSD
        uses: vmactions/freebsd-vm@v1
        with:
          release: "15.1"
          copyback: false
          prepare: |
            pkg install -y ca_root_nss curl gmake
            curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y --profile minimal
          run: |
            . "$HOME/.cargo/env"
            cargo build --verbose
            cargo test --workspace --verbose
